### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by zqlao** [Gaotianhong/LooseLocationSS#1]
Thanks for sharing your great work! Is it possible to get the dataset (whole or partial) in some way to replicate results?

**Comment by Gaotianhong** [comment]
Thank you for your interest in our work! Unfortunately, due to privacy concerns and restrictions, we are unable to publicly share the dataset. However, I would be happy to assist with any questions regarding the data processing or analysis to help you replicate the results. Let me know how I can support you further!

**Comment by zqlao** [comment]
---
Reviewer#3: 
Q5: Address dataset availability. A5: The dataset is being desensitized and reviewed for public release
Reviewer#4: 
Q2: Dataset availability and applying the method to public CRC datasets. A2: Thanks for valuable feedback. Our dataset is being desensitized and reviewed for public release.
---
Thanks for your reply, however, the response is quite different from your responses to the reviewers. I think it makes sense to release at least partial data for replication purpose.

**Comment by Gaotianhong** [comment]
Thank you for your understanding. After further review, the dataset cannot be shared due to privacy restrictions, but I’m happy to assist with any methodological questions.
